# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-26 19:42
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('weightage', models.FloatField(default=0.0)),
                ('metrics', models.TextField()),
                ('dateCreated', models.DateTimeField(default=datetime.datetime(2018, 1, 26, 19, 42, 40, 967206, tzinfo=utc))),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(null=True)),
                ('score', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=datetime.datetime(2018, 1, 26, 19, 42, 40, 967847, tzinfo=utc))),
                ('metric', models.FloatField(default=0.0)),
                ('goalID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GoalApp.Goal')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(blank=True, upload_to='user_profile_pics')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='score',
            name='userID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GoalApp.UserProfile'),
        ),
        migrations.AddField(
            model_name='group',
            name='partner1_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partner1', to='GoalApp.UserProfile'),
        ),
        migrations.AddField(
            model_name='group',
            name='partner2_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partner2', to='GoalApp.UserProfile'),
        ),
        migrations.AddField(
            model_name='goal',
            name='UserID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GoalApp.UserProfile'),
        ),
    ]
